//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hpurchaseinvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hpurchaseinvoice()
        {
            this.dpurchaseinvoices = new HashSet<dpurchaseinvoice>();
            this.purchasepayments = new HashSet<purchasepayment>();
            this.purchaseinvoicenotes = new HashSet<purchaseinvoicenote>();
        }
    
        public long id { get; set; }
        public long projectid { get; set; }
        public string number { get; set; }
        public System.DateTime date { get; set; }
        public long poid { get; set; }
        public long supplierid { get; set; }
        public long diskon { get; set; }
        public long total { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dpurchaseinvoice> dpurchaseinvoices { get; set; }
        public virtual hpo hpo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchasepayment> purchasepayments { get; set; }
        public virtual project project { get; set; }
        public virtual supplier supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchaseinvoicenote> purchaseinvoicenotes { get; set; }
    }
}
