//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hreceiveitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hreceiveitem()
        {
            this.dreceiveitems = new HashSet<dreceiveitem>();
        }
    
        public long id { get; set; }
        public long projectid { get; set; }
        public string number { get; set; }
        public long poid { get; set; }
        public System.DateTime date { get; set; }
        public long supplierid { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dreceiveitem> dreceiveitems { get; set; }
        public virtual hpo hpo { get; set; }
        public virtual project project { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
