//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class hsalesorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hsalesorder()
        {
            this.dsalesorders = new HashSet<dsalesorder>();
            this.salesordernotes = new HashSet<salesordernote>();
        }
    
        public long id { get; set; }
        public long projectid { get; set; }
        public long customerid { get; set; }
        public string number { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime expecteddate { get; set; }
        public string terms { get; set; }
        public string description { get; set; }
        public long grandtotal { get; set; }
        public Nullable<System.DateTime> designdate { get; set; }
        public long total { get; set; }
        public long dp { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dsalesorder> dsalesorders { get; set; }
        public virtual project project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salesordernote> salesordernotes { get; set; }
    }
}
