//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchasepayment
    {
        public long id { get; set; }
        public long projectid { get; set; }
        public long purchaseinvoiceid { get; set; }
        public string number { get; set; }
        public System.DateTime date { get; set; }
        public long supplierid { get; set; }
        public long total { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public string note { get; set; }
    
        public virtual hpurchaseinvoice hpurchaseinvoice { get; set; }
        public virtual project project { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
