//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminLTE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public status()
        {
            this.projects = new HashSet<project>();
        }
    
        public long id { get; set; }
        public byte rfq { get; set; }
        public byte findprices { get; set; }
        public byte penawaran { get; set; }
        public byte salesorder { get; set; }
        public byte purchaseorder { get; set; }
        public byte receiveitem { get; set; }
        public byte purchaseinvoice { get; set; }
        public byte purchasepayment { get; set; }
        public byte suratjalan { get; set; }
        public byte salesinvoice { get; set; }
        public byte salespayment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<project> projects { get; set; }
    }
}
